### ISSUE TITLE
Add package support

### ISSUE THREAD

**Issue by guidezpl** [material-foundation/material-color-utilities#1]
This issue tracks package support for the various languages/platforms.

- [x] Dart: pub.dev
- [ ] Java: Apache Maven
- [x] TypeScript: NPM

**Comment by macintoshhelper** [comment]
Hi, I’ve opened a PR for TypeScript build support for `npm` publishing. Hope this doesn’t conflict with any internal work or build systems, if so feel free to close it. I’ve published a fork to `@elemental-design/material-color-utilities` for those that wish to use this library in an `npm`/Node.js project today.

**Comment by kristiyan-petrov** [comment]
can we re-open the issue? Maven is still missing and we are in 2024...

**Comment by IamRezaMousavi** [comment]
+1

**Comment by evant** [comment]
I've published it myself in the meantime https://github.com/evant/material-color-utilities

**Comment by IamRezaMousavi** [comment]
> I've published it myself in the meantime https://github.com/evant/material-color-utilities

You must have a workflow to update with upstream repo (this repo)

**Comment by IamRezaMousavi** [comment]
> Hi @macintoshhelper, thanks this but I am in the process of preparing a package to publish (likely under the @Material) name. So I'll close the relevant PR.

You can use https://jitpack.io/
